### PR TITLE
Create new componentized metadata frontend.

### PR DESCRIPTION
**Pull request by smlt**
Created a new project under `web` built to have a slightly more decomposed and hopefully more maintainable frontend UI in the future. I used a JSX-based framework for basic state management and decomposition (Preact) but kept everything very minimal on purpose (no frameworks, no design systems, plain old CSS). Tested with the big three browsers and VoiceOver.

Uhh, and no tests. I kept this waiting long enough after I was asked, and maintaining tests would add a pointless burden to future non-frontend friendly devs.

To run the project locally:
1. Install dependencies (`npm install` or `bun install`)
2. Run dev server (`npm run dev` or `bun dev`)
3. And when you're run, build it into a static app (`npm run build` or `bun run build`)

---

Screenshot 2023-11-20 at 19 08 14
Screenshot 2023-11-20 at 19 08 27

### CODE REVIEW

**Comment by emmiegit** [comment]
Very nice! Thanks for your work, I'll review this in more detail when I can.

**Comment by emmiegit** [comment]
Hmm. I see a `package.json` but no `package-lock.json`. Did you forget to commit it?

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /path/to/attribution-metadata/web/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/emmie/attribution-metadata/web/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by smlt** [comment]
@emmiegit That's odd, you can see both `package.json` and `package-lock.json` in the git diff here.

**Comment by emmiegit** [comment]
> @emmiegit That's odd, you can see both `package.json` and `package-lock.json` in the git diff here.

Oh weird. I'll try it again when I'm at home.

**Comment by emmiegit** [comment]
Spent some time playing with this, this is very nice! Thank you so much smlt.

**Review by emmiegit — APPROVED** [review]

**Pull request merged**
